# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, unique=True, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('telphone', models.CharField(max_length=20, verbose_name='电话')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机')),
            ],
        ),
    ]
