# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='room',
            field=models.CharField(default='', max_length=10, verbose_name='房间'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='姓名'),
        ),
    ]
