# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(max_length=20, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
